### PR TITLE
Add compability to HUD bars mod version 1.0.0

### PR DESCRIPTION
**Pull request by Wuzzy2**
This pull request adds **optional** compability to the HUD bars mod. If the HUD bars mod (major version 1) is present, a HUD bar is registered and shown. If the HUD bars mod is not present, the Sprint mod will fall back to its current statbar style.

The icon has been slightly changed, the image has also been renamed in order to follow conventions.

A screenshot of Sprint + HUD bars mod in action (also Mana mod, ignore it for now):
Screenshot of Sprint and HUD bars mod in action.

Also a minor bug is fixed causing the stamina to be able to become slightly larger than `SPRINT_STAMINA` when the stamina has been filled up. Now it is reliably capped at `SPRINT_STAMINA`.

### CODE REVIEW

**Comment by GunshipPenguin** [comment]
Hi,

I tried running this on Minetest 0.4.11 with hudbars 1.0.0 and the latest release of minetest_game. I got the following error:

```
-------------
  Separator  
-------------

Automatically selecting world at [/home/..../Desktop/minetest-0.4.11/bin/../worlds/testworld]
Irrlicht log: Irrlicht Engine version 1.8.1
Irrlicht log: Linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64
Irrlicht log: Using renderer: OpenGL 3.0
Irrlicht log: Gallium 0.4 on AMD CAYMAN: X.Org
Irrlicht log: OpenGL driver version is 1.2 or better.
Irrlicht log: GLSL version: 1.3
16:47:20: ACTION[main]:         .__               __                   __   
16:47:20: ACTION[main]:   _____ |__| ____   _____/  |_  ____   _______/  |_ 
16:47:20: ACTION[main]:  /     \|  |/    \_/ __ \   __\/ __ \ /  ___/\   __\
16:47:20: ACTION[main]: |  Y Y  \  |   |  \  ___/|  | \  ___/ \___ \  |  |  
16:47:20: ACTION[main]: |__|_|  /__|___|  /\___  >__|  \___  >____  > |__|  
16:47:20: ACTION[main]:       \/        \/     \/          \/     \/        
16:47:20: ACTION[main]: World at [/home/..../Desktop/minetest-0.4.11/bin/../worlds/testworld]
16:47:20: ACTION[main]: Server for gameid="minetest_game-0.4.11" listening on 0.0.0.0:55067.
16:47:20: ACTION[ServerThread]: singleplayer [127.0.0.1] joins game. 
16:47:20: ACTION[ServerThread]: singleplayer joins game. List of players: singleplayer
Irrlicht log: Could not load texture: 
Irrlicht log: Could not load texture: 
Irrlicht log: Could not load texture: 
Irrlicht log: Could not load texture: 
Font size: 8 15
16:47:20: ERROR[main]: ServerError: ...Desktop/minetest-0.4.11/bin/../mods/hudbars/init.lua:234: attempt to index field '?' (a nil value)
16:47:20: ERROR[main]: stack traceback:
16:47:20: ERROR[main]: 	...Desktop/minetest-0.4.11/bin/../mods/hudbars/init.lua:234: in function 'unhide_hudbar'
16:47:20: ERROR[main]: 	...Desktop/minetest-0.4.11/bin/../mods/hudbars/init.lua:301: in function 'update_hud'
16:47:20: ERROR[main]: 	...Desktop/minetest-0.4.11/bin/../mods/hudbars/init.lua:331: in function '?'
16:47:20: ERROR[main]: 	...top/minetest-0.4.11/bin/../builtin/game/register.lua:348: in function <...top/minetest-0.4.11/bin/../builtin/game/register.lua:336>
16:47:20: ACTION[ServerThread]: singleplayer leaves game. List of players: 
```
I notice that 1ac3ed1d72f5b9b19545a59d7677a17636255c00 says that you've updated for hudbars 0.3.0. Does this pull request only work with hudbars 0.3.0 or is this just a bug?

**Comment by Wuzzy2** [comment]
It should work with 1.0.0, too, I just did not mention it in seperate commit. Sorry, I can't reproduce it.

So this is probably a bug you see. Can you please just run the HUD bars mod without the stamina mod active?
I would prefer that you test this in the subgame Empty (https://forum.minetest.net/viewtopic.php?f=15&t=11164) to get rid of possible side-effects.

**Comment by Wuzzy2** [comment]
Okay, I have researched a bit and it seems the bug is in the HUD bars mod itself.

Can you please download this experimental version of HUD bars?: http://repo.or.cz/w/minetest_hudbars.git/snapshot/4ebc24f2ed591a617f2d95536c66e9e3c9d765a4.zip

And test it with this version again?

**Comment by GunshipPenguin** [comment]
The expermential version works. Tell me when you've released it and I'll merge this.

**Comment by Wuzzy2** [comment]
Sorry, I have still not made progress on this crash. Not easy to fix. :-/

Could you quickly test if the following change in the experimental branch from bebore helps?:

* Out-comment lines 314, 318, 328 and 346

**Comment by GunshipPenguin** [comment]
So I just tried it with this commit: http://repo.or.cz/w/minetest_hudbars.git?a=commit;h=ef30c34609f0fa9720bf385b67af92597d1e26be

And it worked perfectly. It seems that the link you gave me (http://repo.or.cz/w/minetest_hudbars.git?a=commit;h=4ebc24f2ed591a617f2d95536c66e9e3c9d765a4) was to the master branch. Perhaps I downloaded the experimental branch at one point and that's why it worked.

Was http://repo.or.cz/w/minetest_hudbars.git?a=commith=ef30c34609f0fa9720bf385b67af92597d1e26be the patch that you wanted me to use? If so then it was just a mistake on my part in downloading the wrong commit.

**Comment by Wuzzy2** [comment]
Whoops. Yes, the commit ef30c34609f0fa9720bf385b67af92597d1e26be was the correct one, not the first one I posted. This explains it. :D

Okay, since this commit works, I merge it and release 1.0.1 soon.

**Pull request merged**
